name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    # For frontend
    - name: frontend CI
      run: |
        cd frontend
        npm ci
        npm run build

    # For backend
    - name: backend CI
      run: |
        cd backend
        npm ci
        npm run build
